{
    inpackage: false,
    with-expecter: true,
    testonly: false,
    exported: true,
    outpkg: mockery,
    filename: "{{.InterfaceName}}.{{.PackageName}}.mockery.go",
    mockname: "Mock{{.InterfaceName}}_{{.PackageName}}",
    packages:
        {
            github.com/aws/aws-sdk-go-v2/service/cognitoidentity:
                { interfaces: { Client: {} } },
        },
}
