{
    version: 3,
    tasks:
        {
            buf-bin:
                {
                    platform: ["darwin/amd64", "linux/amd64", "windows/amd64"],
                    generates: ["bin/buf"],
                    dir: "tools",
                    sources: ["**/*", exclude: "bin/**/*"],
                    cmds:
                        [
                            "GOWORK=off go build -mod=vendor -o ./bin/buf github.com/bufbuild/buf/cmd/buf",
                        ],
                },
            mockery-bin:
                {
                    platform: ["darwin/amd64", "linux/amd64", "windows/amd64"],
                    generates: ["bin/mockery"],
                    dir: "tools",
                    sources: ["**/*", exclude: "bin/**/*"],
                    cmds:
                        [
                            "GOWORK=off go build -mod=vendor -o ./bin/mockery github.com/vektra/mockery/v2",
                        ],
                },

            golangci-lint-bin:
                {
                    platform: ["darwin/amd64", "linux/amd64", "windows/amd64"],
                    generates: ["bin/golangci-lint"],
                    dir: "tools",
                    sources: ["**/*", exclude: "bin/**/*"],
                    cmds:
                        [
                            "GOWORK=off go build -mod=vendor -o ./bin/golangci-lint github.com/golangci/golangci-lint/cmd/golangci-lint",
                        ],
                },
            tools: { deps: ["buf-bin", "mockery-bin", "golangci-lint-bin"] },

            buf-gen:
                {
                    deps: ["buf-bin"],
                    generates: ["gen/buf/**/*"],
                    dir: ".",
                    sources: ["proto", "./tools/bin/buf"],
                    cmds:
                        [
                            './tools/bin/buf generate --include-imports --include-wkt --exclude-path="tools/vendor" --template ./buf.gen.yaml --path=./proto',
                        ],
                },

            mockery-gen:
                {
                    deps: ["mockery-bin"],
                    generates: ["gen/mockery/**/*"],
                    dir: ".",
                    sources:
                        ["**/*.go", "./.mockery.yaml", "./tools/bin/mockery"],
                    cmds:
                        [
                            "./tools/bin/mockery --dir ./gen/mockery --config ./.mockery.yaml",
                        ],
                },

            gen: { deps: ["buf-gen", "mockery-gen"] },

            lint:
                {
                    deps: ["golangci-lint-bin"],
                    sources:
                        [
                            "**/*.go",
                            exclude: "tools/**/*",
                            "./tools/bin/golangci-lint",
                        ],

                    cmds: ["./tools/bin/golangci-lint run"],
                },
        },
}
