{
    version: 3,
    tasks:
        {
            buf-bin:
                {
                    generates: ["bin/buf"],
                    dir: "tools",
                    sources: ["**/*", exclude: "bin/**/*"],
                    cmds:
                        [
                            "GOWORK=off go build -mod=vendor -o ./bin/buf github.com/bufbuild/buf/cmd/buf",
                        ],
                },
            mockery-bin:
                {
                    generates: ["bin/mockery"],
                    dir: "tools",
                    sources: ["**/*", exclude: "bin/**/*"],
                    cmds:
                        [
                            "GOWORK=off go build -mod=vendor -o ./bin/mockery github.com/vektra/mockery/v2",
                        ],
                },

            golangci-lint-bin:
                {
                    generates: ["bin/golangci-lint"],
                    dir: "tools",
                    sources: ["**/*", exclude: "bin/**/*"],
                    cmds:
                        [
                            "GOWORK=off go build -mod=vendor -o ./bin/golangci-lint github.com/golangci/golangci-lint/cmd/golangci-lint",
                        ],
                },

            gotestsum-bin:
                {
                    generates: ["bin/gotestsum"],
                    dir: "tools",
                    sources: ["**/*", exclude: "bin/**/*"],
                    cmds:
                        [
                            "GOWORK=off go build -mod=vendor -o ./bin/gotestsum gotest.tools/gotestsum",
                        ],
                },

            bun-bin:
                {
                    platforms:
                        [
                            "linux/amd64",
                            "darwin/amd64",
                            "linux/arm64",
                            "darwin/arm64",
                        ],
                    preconditions: ["which unzip", "which curl"],
                    status: ["bun --version"],
                    cmds: ["curl -fsSL https://bun.sh/install | bash"],
                },

            cdk-bin:
                {
                    generates: ["node_modules/.bin/cdk"],
                    dir: "infrastructure/bun",
                    deps: ["bun-bin"],
                    sources: ["package.json", "bun.lockb"],
                    cmds: ["bun install"],
                },

            tools:
                {
                    deps:
                        [
                            "buf-bin",
                            "mockery-bin",
                            "golangci-lint-bin",
                            "gotestsum-bin",
                            "cdk-bin",
                            "bun-bin",
                        ],
                },

            buf-gen:
                {
                    deps: ["buf-bin"],
                    generates: ["gen/buf/**/*"],
                    dir: ".",
                    sources: ["proto/**/*.proto", "./tools/bin/buf"],
                    cmds:
                        [
                            './tools/bin/buf generate --include-imports --include-wkt --exclude-path="tools/vendor" --template ./buf.gen.yaml --path=./proto',
                        ],
                },

            mockery-gen:
                {
                    deps: ["mockery-bin"],
                    generates: ["gen/mockery/**/*"],
                    dir: ".",
                    sources:
                        ["**/*.go", "./.mockery.yaml", "./tools/bin/mockery"],
                    cmds:
                        [
                            "./tools/bin/mockery --dir ./gen/mockery --config ./.mockery.yaml",
                        ],
                },

            gen: { deps: ["buf-gen", "mockery-gen"] },

            cdk-synth:
                {
                    deps: ["cdk-bin"],
                    dir: "infrastructure",
                    generates: ["cdk.out"],
                    sources: ["**/*.go", "./.cdk.json"],
                    cmds: ["./bun/node_modules/.bin/cdk synth"],
                },

            lint:
                {
                    deps: ["golangci-lint-bin"],
                    sources:
                        [
                            "**/*.go",
                            exclude: "tools/**/*",
                            "./tools/bin/golangci-lint",
                        ],

                    cmds:
                        [
                            "GOWORK=off ./tools/bin/golangci-lint run --config ./.golangci.yml",
                        ],
                },

            test:
                {
                    deps: ["gotestsum-bin"],
                    sources:
                        [
                            "**/*.go",
                            exclude: "tools/**/*",
                            "./tools/bin/gotestsum",
                        ],

                    cmds:
                        [
                            "GOWORK=off ./tools/bin/gotestsum --format=junit --raw-command -- -coverprofile=coverage.out ./...",
                        ],
                },

            default: { deps: ["tools", "gen", "lint", "test"] },
        },
}
