version: "3.8"
services:
    appsync:
        container_name: appsync-authorizer
        ports:
            - "9000:8080"
        platform: "linux/arm64"
        build:
            dockerfile: Dockerfile.lambda
            args:
                CMD: "lambda/appsync-authorizer/main.go"
        volumes:
            - ~/.aws-lambda-rie:/aws-lambda
        entrypoint:
            - /aws-lambda/aws-lambda-rie
            - /var/task/handler
        environment:
            - APPLE_JWT_PUBLIC_KEY_ENDPOINT=https://appleid.apple.com/auth/keys
            - CHALLENGE_TABLE_NAME=unused
            - APPLE_IDENTITY_POOL_ID=unused
    apigw:
        container_name: apigw-authorizer
        ports:
            - "9001:8081"
        platform: "linux/arm64"
        build:
            dockerfile: Dockerfile.lambda
            args:
                CMD: "lambda/apigw-authorizer/main.go"
        volumes:
            - ~/.aws-lambda-rie:/aws-lambda
        entrypoint:
            - /aws-lambda/aws-lambda-rie
            - /var/task/handler
        environment:
            - APPLE_JWT_PUBLIC_KEY_ENDPOINT=https://appleid.apple.com/auth/keys
            - CHALLENGE_TABLE_NAME=unused
            - APPLE_IDENTITY_POOL_ID=unused
    challenge:
        container_name: challenge
        ports:
            - "9002:8082"
        platform: "linux/arm64"
        build:
            dockerfile: Dockerfile.lambda
            args:
                CMD: "lambda/challenge/main.go"
        volumes:
            - ~/.aws-lambda-rie:/aws-lambda
        entrypoint:
            - /aws-lambda/aws-lambda-rie
            - /var/task/handler
        environment:
            - APPLE_JWT_PUBLIC_KEY_ENDPOINT=https://appleid.apple.com/auth/keys
            - CHALLENGE_TABLE_NAME=unused
            - APPLE_IDENTITY_POOL_ID=unused
    register:
        container_name: register
        ports:
            - "9003:8083"
        platform: "linux/arm64"
        build:
            dockerfile: Dockerfile.lambda
            args:
                CMD: "lambda/register/main.go"
        volumes:
            - ~/.aws-lambda-rie:/aws-lambda
        entrypoint:
            - /aws-lambda/aws-lambda-rie
            - /var/task/handler
        environment:
            - APPLE_JWT_PUBLIC_KEY_ENDPOINT=https://appleid.apple.com/auth/keys
            - CHALLENGE_TABLE_NAME=unused
            - APPLE_IDENTITY_POOL_ID=unused
