version: "3.8"
services:
    appsync:
        container_name: apple-appsync
        ports:
            - "9000:8080"
        platform: "linux/arm64"
        build:
            dockerfile: Dockerfile.lambda
            args:
                CMD: "cmd/apple-appsync/main.go"
        volumes:
            - ~/.aws-lambda-rie:/aws-lambda
        entrypoint:
            - /aws-lambda/aws-lambda-rie
            - /var/task/handler
        environment:
            - APPLE_JWT_PUBLIC_KEY_ENDPOINT=https://appleid.apple.com/auth/keys
            - CHALLENGE_TABLE_NAME=unused
            - APPLE_IDENTITY_POOL_ID=unused
    apigw:
        container_name: apple-apigw
        ports:
            - "9001:8081"
        platform: "linux/arm64"
        build:
            dockerfile: Dockerfile.lambda
            args:
                CMD: "cmd/apple-apigw/main.go"
        volumes:
            - ~/.aws-lambda-rie:/aws-lambda
        entrypoint:
            - /aws-lambda/aws-lambda-rie
            - /var/task/handler
        environment:
            - APPLE_JWT_PUBLIC_KEY_ENDPOINT=https://appleid.apple.com/auth/keys
            - CHALLENGE_TABLE_NAME=unused
            - APPLE_IDENTITY_POOL_ID=unused
    challenge:
        container_name: challenger
        ports:
            - "9002:8082"
        platform: "linux/arm64"
        build:
            dockerfile: Dockerfile.lambda
            args:
                CMD: "cmd/challenge/main.go"
        volumes:
            - ~/.aws-lambda-rie:/aws-lambda
        entrypoint:
            - /aws-lambda/aws-lambda-rie
            - /var/task/handler
        environment:
            - APPLE_JWT_PUBLIC_KEY_ENDPOINT=https://appleid.apple.com/auth/keys
            - CHALLENGE_TABLE_NAME=unused
            - APPLE_IDENTITY_POOL_ID=unused

