{
    name: Auto Increment Tag,
    on: { push: { branches: [main] } },
    permissions: { contents: write, packages: write },
    jobs:
        {
            auto-tag:
                {
                    runs-on: ubuntu-latest,
                    steps:
                        [
                            {
                                name: Checkout code,
                                uses: actions/checkout@v3,
                                with: { fetch-depth: 0 },
                            },
                            {
                                name: Bump version and push tag,
                                id: tag_version,
                                uses: anothrNick/github-tag-action@1.61.0,
                                env:
                                    {
                                        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
                                        WITH_V: true,
                                        DEFAULT_BUMP: patch,
                                        DRY_RUN: true,
                                    },
                            },
                            {
                                name: Create GitHub Release,
                                if: success(),
                                uses: ncipollo/release-action@v1,
                                env:
                                    {
                                        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
                                    },
                                with:
                                    {
                                        tag: "${{ steps.tag_version.outputs.tag }}",
                                        name: "${{ steps.tag_version.outputs.tag }}",
                                        body: "Auto-generated release for ${{ steps.tag_version.outputs.tag }}",
                                        draft: false,
                                        prerelease: false,
                                    },
                            },
                        ],
                },
        },
}
